dist: trusty
language: ruby

services:
  - docker

rvm:
  - 2.4.1

cache:
  bundler: true

env:
  matrix:
    - TEST_INSTANCE=2x-chef12-ubuntu-xenial
    - TEST_INSTANCE=2x-chef12-centos-centos7

script:
  - |
    set -ex -o pipefail
    bundle exec kitchen test "${TEST_INSTANCE}"
